eureka:
  client:
    service-url:
      defaultZone: http://z02.demo08.haproxy-192-168-1-117-alaudademo08.myalauda.cn:8000/eureka/
server:
  port: 8001
spring:
  application:
    name: eureka-client-maxvalue
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  thymeleaf:
    cache: false
    mode: HTML5






